### ISSUE TITLE
Elude Demos Inverted Colors

### ISSUE THREAD

**Issue by pcotter72** [michalsc/Emu68#156] opened 2022-03-15 09:06 UTC
Elude demos display inverted colors.
White should be black.
Example, Kakao demo

https://youtu.be/MX-Dd_uFmaA?t=52

Good:
https://youtu.be/nXutiImaqZs?t=43

**Comment by michalsc** [comment] 2022-05-03 11:38
The issue is fixed with commit eba24b1.

**Closed by michalsc** 2022-05-03 11:38 UTC
